@startuml
storage "Training dataset" as usecase1
rectangle "Standardization of the training set by resizing and augmentation" as rectangle1
rectangle "Input layer" as rectangle2
rectangle "Repeated 6x" as rectangle3 {
rectangle "Convolutional layer" as rectangle3.1
rectangle "Batch normalization layer" as rectangle3.2
rectangle "ReLU layer" as rectangle3.3
rectangle "Pooling layer" as rectangle3.4
}
rectangle "Flatten layer" as rectangle4
rectangle "Training network with given parameters" as rectangle5
rectangle "Creation of confusion matrices and calculation of network effectivnes" as rectangle6 
usecase1 --> rectangle1
rectangle1 --> rectangle2
rectangle2 --> rectangle3
rectangle3 --> rectangle3.1
rectangle3.1 --> rectangle3.2
rectangle3.2 --> rectangle3.3
rectangle3.3 --> rectangle3.4
rectangle3.4 --> rectangle4
rectangle4 --> rectangle5
rectangle5 --> rectangle6


@enduml